namespace PaleLotus.CsvSourceGenerator;

internal sealed record TypeToGenerate
{
    public string TypeName { get; }
    private string Namespace { get; }
    private string AccessModifiers { get; }
    private string DataType { get; }
    private EquatableArray<string> Properties { get; }

    public TypeToGenerate(string typeName,
        List<string> values,
        string accessModifiers,
        string dataType, string nameSpace)
    {
        TypeName = typeName;
        AccessModifiers = accessModifiers;
        DataType = dataType;
        Namespace = nameSpace;
        Properties = new EquatableArray<string>(values.ToArray());
    }


    public string Generate()
    {
        var properties = string.Join(",",Properties.Select(str => str.Replace(str, $$"""{nameof(this.{{str}})}""")));
        
        var template = $$"""
                         //------------------------------------------------------------------------------
                         // <auto-generated>
                         //     This code was generated by the PaleLotus.CsvSourceGenerator source generator
                         //
                         //     Changes to this file may cause incorrect behavior and will be lost if
                         //     the code is regenerated.
                         // </auto-generated>
                         //------------------------------------------------------------------------------
                         
                         namespace {{Namespace}}
                         {
                             {{AccessModifiers}} partial {{DataType}} {{TypeName}} : FreeDoomBridge.SourceGenerators.ICsvSerializable
                             {
                             
                                public string ToCsv() => $"{{properties}}";
                                public string GetCsvHeader() => $"{{string.Join(",", Properties)}}";
                             }
                         }
                         """;
        return template;
    }
}